### ISSUE TITLE
'Eigen/Eigen' file not found

### ISSUE THREAD

**Issue by Chrismomo** [libfive/libfive#144]
### Description

While `make` in the build folder, the it shows `'Eigen/Eigen' file not found`. I'm sure that the Eigen has been installed in my computer under `/usr/local/include` shown as pic below: 

<img width="570" alt="2018-02-24 2 44 42" src="https://user-images.githubusercontent.com/4274050/36626645-96f46dec-1971-11e8-8522-d8ce3587d20a.png">

**Comment by mkeeter** [comment]
What is the exact log message?  What happens if you run with `VERBOSE=1 make` to see the actual commands that are being run?

I installed Eigen through homebrew, and it was installed in `/usr/local/include/eigen3/`, rather than `/usr/local/include/Eigen`; are you sure that you're using Eigen 3.3.0 or later?

**Comment by Chrismomo** [comment]
The log message can seen in the following screenshots. And I've also installed Eigen through homebrew, but because of the log message mentioning `Eigen/Eigen`, I tried to rename the folder under `/usr/local/include/`. It worked the same when its name was eigen3.

👇After running `make`
<img width="587" alt="2018-02-25 10 13 32" src="https://user-images.githubusercontent.com/4274050/36642339-27eb3d1e-1a79-11e8-9163-956585473b9f.png">

👇After running `make VERBOSE=1`
<img width="581" alt="2018-02-25 10 14 33" src="https://user-images.githubusercontent.com/4274050/36642353-5831a01c-1a79-11e8-9922-6105ced2c43e.png">

**Comment by mkeeter** [comment]
Oh, it looks like you've run CMake against the wrong directory.  Your build directory should be at 
`/Users/xinyuehou/Desktop/fab/libfive/build`, rather than 
`/Users/xinyuehou/Desktop/fab/libfive/libfive/build`

**Comment by Chrismomo** [comment]
Yep! It has successfully built on my computer!!!
Thanks!!!!!  I'm gonna to play with libfive now~~~
