### ISSUE TITLE
Libfive no longer builds on Ubuntu 16.04

### ISSUE THREAD

**Issue by doug-moen** [libfive/libfive#147]
Due to recent changes to CMakeLists.txt, Libfive no longer builds on Ubuntu 16.04.

The problem is that Libfive now requires Eigen 3.3.0 or greater, whereas Ubuntu 16.04 has Eigen 3.2.92. I don't have any problem running libfive with Eigen 3.2.92, that I'm aware of.

Note that on Ubuntu 16.04, the "libeigen3-dev" package is identified as having version "3.3~beta1-2" by the package manager, but the file /usr/lib/cmake/eigen3/Eigen3Config.cmake identifies the Eigen3 library as having version 3.2.92, and the latter is what Cmake cares about.

I have fixed this problem in a fork of libfive by changing CMakeLists.txt to require Eigen 3.2.92 or later.

**Comment by mkeeter** [comment]
Fixed in the PR.
