### ISSUE TITLE
Opcodes clash with Windows macros CONST, EXP, MIN, MAX, MOD

### ISSUE THREAD

**Issue by igfraga** [libfive/libfive#156]
Opcodes clash with Windows macros CONST, EXP, MIN, MAX, MOD

Unfortunately Windows.h defines these and many more ugly macros.
So including Windows.h before opcode.hpp will prevent the code from compiling.
Because of this we are forced to always include libfive at the very top of our source files.

In our codebase at nTopology we prefix all enums with "e_" to avoid this. This is just one possible solution of course.

**Comment by mkeeter** [comment]
Can you see if the `rename-opcodes` branch works?

I couldn't find a full list of the `Windows.h` macros, but renamed all of the opcodes that looked suspicious.

**Comment by speps** [comment]
Did you check if defining NOMINMAX and WIN32_LEAN_AND_MEAN also fix the problem?

**Comment by igfraga** [comment]
The rename-opcodes branch works!

NOMINMAX and WIN32_LEAN_AND_MEAN are not enough (CONST for example seems to get in there with Windows.h)

**Comment by mkeeter** [comment]
Great, merged.
