### ISSUE TITLE
Degree symbol (º) breaks unit tests

### ISSUE THREAD

**Issue by mkeeter** [libfive/libfive#161]
### Description
Unit tests fail with
```
guile: uncaught throw to read-error: (scm_lreadr #<unknown port>:410:18: unknown character name ~a (??) #f)
```

Suspiciously enough, at [line 410 of text.scm](https://github.com/libfive/libfive/blob/master/libfive/bind/text.scm#L410-L411), we have a unicode character (currently commented out).

### Versions

- Operating system: Mac
- `libfive` commit hash: 5952bbf49fa

**Comment by pdu4** [comment]
I put the degree symbol in when I [ported the rest of the letters][1] from Antimony. I use degrees in my drawings and I didn't think unicode was unacceptable and it worked on my computer with no problems as I have the degree symbol on my keyboard (I didn't do the unit tests). I'll try to keep any others I do within ASCII specs. 


[1]:https://github.com/libfive/libfive/issues/157#issuecomment-377018018
