### ISSUE TITLE
Install/build instructions for libfive?

### ISSUE THREAD

**Issue by hech92** [libfive/libfive#162]
EDIT: Apparently I am blind and overlooked the instructions, so ignore this please.

Hello,

I installed all dependencies and built guile-2.2 from source (with the instructions given for Ubuntu in the readme), but I couldn't find any installation instructions for libfive (and libfive-guile) itself for Linux (I'm using Linux Mint). I'm rather new to Linux, could anybody help me out here please?
I know that I must clone the git repository but don't know how to build/install from the code.

**Comment by mkeeter** [comment]
Okay, ignoring this :)
