### ISSUE TITLE
What to call a reflect that duplicates?

### ISSUE THREAD

**Issue by omgitsraven** [libfive/libfive#173]
I want to add a function that I usually call "mirror", which is just `(remap-shape shape (x y z) (abs x) y z)`, for making symmetrical things like faces. I'm just not sure what name would be appropriate, given there's already a `reflect-x` that would be easily confused with `mirror-x`? Should it maybe be added as an optional boolean argument to `reflect-x`? Or should I go with something like `symmetry-x` or `symmetrical-x`? (The trouble is there's no real verb form of "symmetry"...)

**Comment by mkeeter** [comment]
Yeah, the lack of verb is unfortunate; I'd vote for `symmetric-x` as the best option.
