### ISSUE TITLE
Incorrect results for intersecting solids with plane in common.

### ISSUE THREAD

**Issue by Paul-Wray** [libfive/libfive#187]
The code below should form a hollow tube, but the bottom plane is filled.
If the box starts at z=0.1 instead of 0, it works OK.

Must I ensure intersecting solids don't have common surfaces, as with openscad? 
I thought I had noticed that libfive handled these cases correctly.

```
(intersection
  (box [-50 -50 0][50 50 10])
  (difference 
    (cylinder 10 100)
    (cylinder 5 100)
  )
)
```

**Comment by mkeeter** [comment]
It usually does, so I'll check this model out.

**Comment by mkeeter** [comment]
Fixed in the commit above; thanks for noticing and reporting this edge case!
