### ISSUE TITLE
Build failing on Ubuntu 16.04 with Gcc 6.4

### ISSUE THREAD

**Issue by dilevin** [libfive/libfive#195]
I'm getting an odd build error on Ubuntu 16.04:

In file included from /usr/include/boost/lockfree/stack.hpp:13:0,
                 from /home/dilevin/Assignments/ThirdParty/libfive/libfive/src/render/brep/xtree_pool.cpp:27,
                 from /home/dilevin/Assignments/ThirdParty/libfive/libfive/src/render/brep/xtree_pool2.cpp:19:
/usr/include/boost/lockfree/stack.hpp: In instantiation of ‘class boost::lockfree::stack<Kernel::Task<2u>, boost::lockfree::fixed_sized<true>, boost::parameter::void_, boost::parameter::void_>’:
/home/dilevin/Assignments/ThirdParty/libfive/libfive/src/render/brep/xtree_pool.cpp:179:22:   required from ‘static typename Kernel::XTree<N>::Root Kernel::XTreePool<N>::build(Kernel::XTreeEvaluator*, Kernel::Region<N>, double, double, unsigned int, std::atomic_bool&) [with unsigned int N = 2u; typename Kernel::XTree<N>::Root = Kernel::XTree<2u>::Root; std::atomic_bool = std::atomic<bool>]’
/home/dilevin/Assignments/ThirdParty/libfive/libfive/src/render/brep/xtree_pool2.cpp:24:17:   required from here
/usr/include/boost/lockfree/stack.hpp:73:5: error: static assertion failed: boost::has_trivial_assign<T>::value
     BOOST_STATIC_ASSERT(boost::has_trivial_assign<T>::value);
     ^
/usr/include/boost/lockfree/stack.hpp:74:5: error: static assertion failed: boost::has_trivial_destructor<T>::value
     BOOST_STATIC_ASSERT(boost::has_trivial_destructor<T>::value);

Any idea what is causing this ?

**Comment by mkeeter** [comment]
Perhaps a mismatch in Boost version?

I'm compiling against Boost 1.67; can you check what version you're using?

**Comment by dilevin** [comment]
ah that did it, I was using 1.58.

Thanks!
