### ISSUE TITLE
Text Editor not updating in Ubuntu under Wayland

### ISSUE THREAD

**Issue by rcmz** [libfive/libfive#203]
### Description

I am using Gnome under Wayland on Ubuntu 18.04 and the text editor is not updating visually until I click on the viewport. It works fine on Xorg though.

### Versions

- Operating system: Ubuntu 18.04, Gnome, Wayland

**Comment by mkeeter** [comment]
This is a duplicate of #59.  For now, the fix is to not use Wayland; if any Linux gurus would like to debug, then help is welcome.
