### ISSUE TITLE
export-meshes fails due to an env error

### ISSUE THREAD

**Issue by mayjs** [libfive/libfive#235]
### Description

When running `export-meshes`, the script crashes to due a `/usr/bin/env` error:
```
/usr/bin/env: ‘guile --no-auto-compile -s’: No such file or directory
/usr/bin/env: use -[v]S to pass options in shebang lines
```

### Versions

- Operating system: Arch Linux
- `libfive` commit hash: `a2401415`
  - Is this the latest commit to `master`?  yes

### Additional Information

Applying the fix suggested by `/usr/bin/env` fixes the error, I might submit a PR later.

**Comment by mkeeter** [comment]
Okay – I don't support Arch Linux myself, so a PR is welcome!
