### ISSUE TITLE
Compilation issue on Arch Linux

### ISSUE THREAD

**Issue by metafex** [libfive/libfive#247]
Currently when trying to build it on arch, it errs out after a bit with a whole lot of compilation errors which start with this:

`libfive-git/src/libfive/libfive/src/../include/libfive/eval/tape.hpp:42:18: error: ‘shared_ptr’ in namespace ‘std’ does not name a template type`

Just adding `#include <memory>` to tape.hpp seems to fix this.

**Comment by zoe1337** [comment]
I can confirm this. Tried building from AUR, then directly from git master branch. @metafex 's recommendation worked.

**Comment by mkeeter** [comment]
Thanks, fixed in the commit above.
