### ISSUE TITLE
How to create a capped Cone? 

### ISSUE THREAD

**Issue by af3dgce** [libfive/libfive#252]

**Comment by mkeeter** [comment]
```
(intersection
  (cone 1 1 [0 0 0])
  (lambda-shape (x y z) (- z 0.5)))
```
<img width="951" alt="Screen Shot 2019-03-24 at 9 52 09 AM" src="https://user-images.githubusercontent.com/745333/54880394-80e33180-4e1a-11e9-8e60-98c233166618.png">
