### ISSUE TITLE
If /cond goops-error

### ISSUE THREAD

**Issue by pdu4** [libfive/libfive#264]
### Description

in some situations, the functions "if" and "cond" do not take options that don't do anything.
e.g

     (union (box [0 0 0 ] [ 1 1 1])
        (if test
          (cylinder  2.5 2 [3 0 0] ))i
	    )
  
fails if test is not true. siting this error

         goops-error: No applicable method for #<<generic> min (4)> in call (min #<<shape> 5f7627bc05c0> #<unspecified>)

It only works if you put another object in the else form 
i.e 

     (union (box [0 0 0 ] [ 1 1 1])
        (if test
           (cylinder  2.5 2 [3 0 0] )
	      (box [1 1 1] [2 2 2])
	      ))
 

false(#f) and also pure math expressions do not work in the else form either giving the same error. is there a no-op or something that can be used? 

The same thing happens for cond and Difference 
However if only using "if" without the union it works as does union with only one argument 

Of course I can make two different object and use if to draw one or the other but this will end up quite verbose as I will be repeating the same code.

Also on a less important note, "begin" does not work as (I) expected either, it only draws the last object given but union can replace it for now it is not really an issue.

### Versions

- Operating system: Debian
- `libfive` commit hash: [2690d86+]
  - Is this the latest commit to `master`?  [No]
- Qt version (if applicable): 5

**Comment by mkeeter** [comment]
I think this is behaving correctly, based on how conditionals without an `else` branch work.  The `if` statement returns `#<unspecified>` if there isn't an `else` branch, and you can't take `(union (box ...) #<unspecified>)`

Removing the `libfive`-specific functions, here's a minimal example:
```
(define test #t)
(+ 1 (if test 1))
```
If you change `test` to `#f`, then this will throw a similar error:
```
goops-error: No applicable method for #<<generic> + (10)> in call (+ 1 #<unspecified>)
```

You are on the right track when you asked
>is there a no-op or something that can be used?

In 92b298613d2e50e64c98dbeb39b5deb14910f991, I've added `emptiness`, which is exactly what it sounds like.  Your example can be written as
```
(define test #f)
(union (box [0 0 0 ] [ 1 1 1])
    (if test
      (cylinder  2.5 2 [3 0 0])
      (emptiness))
    )
```
and behaves as expected.
