### ISSUE TITLE
Issues with assert not in scope when building in Docker and Ubuntu

### ISSUE THREAD

**Issue by stuartlynn** [libfive/libfive#270]
### Description

Building on Ubuntu 18.04 and building in the dockerfile is resulting in errors about "assert" not being declared in scope

```
/home/stuart/build/libfive/libfive/src/render/brep/progress.cpp: In destructor ‘Kernel::ProgressWatcher::~ProgressWatcher()’:
/home/stuart/build/libfive/libfive/src/render/brep/progress.cpp:84:5: error: ‘assert’ was not declared in this scope
     assert(done.load() || cancel.load());
     ^~~~~~
/home/stuart/build/libfive/libfive/src/render/brep/progress.cpp:84:5: note: suggested alternative: ‘qsort’
     assert(done.load() || cancel.load());
     ^~~~~~
     qsort
libfive/src/CMakeFiles/five.dir/build.make:422: recipe for target 'libfive/src/CMakeFiles/five.dir/render/brep/progress.cpp.o' failed
``` 

Adding 

```c
#include <cassert>
```
to libfive/include/libfive/render/brep/object_pool.hpp and libfive/src/render/brep/progress.cpp

seems to resolve this. 
### Versions

- Operating system: Ubuntu 18.04
- `libfive` commit hash: https://github.com/libfive/libfive/commit/3e45aa1af16f0356431de3b22886d097d00830ee
  - Is this the latest commit to `master`?  yes

### Additional Information

I opened a pull request that implements these changes but if there is a better way to fix this, or if I am getting this error because I am doing something wrong please let me know!

**Comment by mkeeter** [comment]
Yup, that's the right thing to do – thanks for the PR!
