### ISSUE TITLE
'floor' function?

### ISSUE THREAD

**Issue by andybak** [libfive/libfive#293]
I've been trying to convert various SDF algorithms from Inigo Quilez et al

I needed a fract function which is defined thus:

    (define (fract v) (- v (floor v)))

However "floor" doesn't work inside lambda-shape due to a type mismatch.

    (floor x)
    
    In function floor: wrong-type-arg

Any suggestions how to work round this?

Is there a list of all the maths functions that do work inside lambda-shape?

**Comment by mkeeter** [comment]
You can get the fractional part with `modulo`, e.g.

```
(define-shape (s x y z) (modulo x 1))
(shape-eval s [1.3 0 0]) ;; returns 0.3
```

The list o' shapes isn't anywhere user-friendly, but it's in the [`libfive-guile.cpp` source](https://github.com/libfive/libfive/blob/master/libfive/bind/libfive-guile.cpp#L451-L494).
