### ISSUE TITLE
Link to studio examples folder from website

### ISSUE THREAD

**Issue by kasbah** [libfive/libfive#311]
Hey, I think it would be a good idea to link to the [studio examples folder](https://github.com/libfive/libfive/tree/master/studio/examples) from the [example page](https://libfive.com/examples/). I would have liked to know about these working examples sooner but just stumbled across them. 

Also, if website source is on Github (maybe I missed it?) would be happy to submit a pull-requests for stuff like this.

**Comment by mkeeter** [comment]
Good idea, done!

(the website isn't on Github yet, but I'll get around to it eventually)
