### ISSUE TITLE
Support building with Guile 3

### ISSUE THREAD

**Issue by rekado** [libfive/libfive#324]
Guile 3 will be released soon.  Libfive cannot currently be built with Guile 2.9.7 (which self-reports as Guile 3.0).

It might be sufficient to adjust the CMakeLists.txt to search for `guile-3.0` before `guile-2.2`.

**Comment by rekado** [comment]
This is related: https://github.com/libfive/libfive/pull/301

**Comment by mkeeter** [comment]
Fixed in 8ca1b8685ef3fac7b64e66b10459b8421a3020c6
