### ISSUE TITLE
Revolve `x0` not used?

### ISSUE THREAD

**Issue by KoviRobi** [libfive/libfive#343]
Perhaps I'm being silly, but the `x0` optional argument isn't used in revolve

https://github.com/libfive/libfive/blob/e1da2fb6c2171a399c9a109e99e83d704310a6e2/libfive/bind/transforms.scm#L380-L387

**Comment by KoviRobi** [comment]
I also wonder how do can I make a corkscrew shape, e.g.
```
(define* (revolve-y shape #:optional (x0 0))
  "revolve-y shape [x0]
  Revolves a 2D (xy) shape around the vertical line x=x0"
  (union
    (remap-shape (shape x y z)
      (sqrt (+ (square x) (square z))) (- y (atan x z)) z)
    (remap-shape (shape x y z)
      (- (sqrt (+ (square x) (square z)))) (- y (atan x z)) z)))
(revlove-y (circle 1 #[10 0]))
```
doesn't produce anything neat (probably because of the discontinuity, but then how do I make it infinite?)

**Comment by mkeeter** [comment]
This got ported to the C++ standard library, and now [uses `x0`](https://github.com/libfive/libfive/blob/master/libfive/stdlib/stdlib_impl.cpp#L538-L544)!
