### ISSUE TITLE
Building in ubuntu 18.04.5 LTS : needed libqt5opengl5-dev

### ISSUE THREAD

**Issue by awgrover** [libfive/libfive#361]
### Description

[Description of the issue]
Needed an extra dependency: `libqt5opengl5-dev` (maybe just `libqt5opengl5`?)

[Steps to reproduce]
sudo apt-get install cmake pkg-config libeigen3-dev libpng-dev libboost-all-dev qtbase5-dev guile-2.2-dev
mkdir build
cd build
cmake -DCMAKE_PREFIX_PATH=/usr/include/x86_64-linux-gnu/qt5

[What did you expect to happen?]  
...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/awgrover/dev/thirdparty/libfive/build

[What happened?  All the time?]
All the time:
I failed to capture the exact output before I fixed it which makes it difficult to reproduce.
The cmake step complained about a missing "package config" for "Qt5opengl", and how it tried to search for some .cmake files for Qt5opengl.

[Are there any error messages printed to the console?]
As vaguely noted above.

### Versions

- Operating system: [here] Ubuntu 18.04.5 LTS
    apt-get upgrade'd very recently
- `libfive` commit hash: [here] 8ca1b8685ef3fac7b64e66b10459b8421a3020c6
  - Is this the latest commit to `master`?  yes
- Qt version (if applicable): 5.9.5
  qtbase5-dev 5.9.5+dfsg-0ubuntu2.5
  libqt5concurrent5:amd64     5.9.5+dfsg-0ubuntu2.5
  libqt5opengl5-dev:amd64     5.9.5+dfsg-0ubuntu2.5

### Additional Information
I guessed at the CMAKE_PREFIX_PATH. Not sure if it even matters.

Looks like it works:
After adding libqt5opengl5-dev, it cmake'd and then make'd. Studio ran and opened a window with the initial empty geometry rendered (xyz "cones"), and draggable. 

Rendered and draggable:
(difference (sphere 1 [0 0 0])
  (sphere 0.6 [0 0 0])
  (cylinder-z 0.6 2 [0 0 -1])
  (reflect-xz (cylinder-z 0.6 2 [0 0 -1]))
  (reflect-yz (cylinder-z 0.6 2 [0 0 -1])))
  

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by mkeeter** [comment]
Closing because we're now pinning builds to the latest Ubuntu LTS (currently 20.04).
