### ISSUE TITLE
Studio can't be double-clicked on Ubuntu

### ISSUE THREAD

**Issue by omgitsraven** [libfive/libfive#380]
### Description

After building on Ubuntu, the Studio file that results just has a generic 'text document' icon, and double-clicking it produces the following error:
![image](https://user-images.githubusercontent.com/8540042/107840468-fa72c880-6d80-11eb-98ff-f2d835a4fd16.png)

It can still be run from the command line, but older versions of Studio didn't require this workaround, so it would be nice to fix if possible.

### Versions

- Operating system: Ubuntu 18.04.5 LTS
- `libfive` commit hash: 30203ffd710101c7811283e14f16a975b15c2dd7
  - Is this the latest commit to `master`?  yes
- Qt version (if applicable): 5.9.5

### Additional Information

It's quite possible that this isn't a change in the Studio *source*, but rather a change in my build process, which has had to deviate significantly from the recommended one in order to successfully build the latest version (which I plan on bringing up as a separate issue once this is resolved...)

I've seen threads online that suggest that this issue can be related to Qt (which is one of the changes I made to the build process; letting the Qt version be implied rather than specifying it manually) but I'm in over my head enough not to be sure how to move forward with this (I barely got it building again at all...)

For reference, here is my current build process:
```
export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig
cmake -DCMAKE_C_COMPILER=gcc-7 -DCMAKE_CXX_COMPILER=g++-7 ..
make -j4
```
I'm open to any suggested changes at this point.

**Comment by smilberger** [comment]
I'm on Ubuntu 18.04, I get the same thing.  If you right click on the executable in the file manager, then select "Properties", and look at the "Basic" tab in the "Type" field, you will probably see "shared library (application/x-sharedlib)" (you might have to resize the window to see the whole thing.)  The desktop won't run it as an executable unless it is "application/x-executable" (the MIME type). It looks like this is a problem with how gcc [sets a flag](https://stackoverflow.com/questions/41398444/gcc-creates-mime-type-application-x-sharedlib-instead-of-application-x-applicati) in the binary.  Many of my executables are like this on Ubuntu now.

There are some ideas in that SO issue that might help you or, you could create a Gnome Desktop file to work around it, [here](https://github.com/nwjs/nw.js/issues/5287).
