### ISSUE TITLE
libfive Studio for Windows 10 and Gnu/Linux

### ISSUE THREAD

**Issue by JuanJ67m** [libfive/libfive#391]
where or when can I download a Windows 10 and Gnu/Linux for Libfive Studio?

**Comment by mkeeter** [comment]
The full Studio GUI isn't supported on Windows 10, and there aren't pre-compiled binaries for Linux.

For details on building from source, please read [the "Building" section of the README](https://github.com/libfive/libfive#compiling-from-source).
