### ISSUE TITLE
Mention in readme that `sudo make install` should be run on each build?

### ISSUE THREAD

**Issue by omgitsraven** [libfive/libfive#412]
I was just pulling my hair out trying to figure out why my builds were saying they came from an older commit hash even though `git fetch` was working, until I finally realised, if I ran `studio/Studio` it would show the latest hash, and if I ran my shortcut, it would show the older one. Running `sudo make install` again has fixed that, but it didn't occur to me to try it for a while; I thought it would only change the .desktop file...

**Comment by mkeeter** [comment]
Okay, done in b45ae90c99ac34425b6f022539d4e70ca240269f
