### ISSUE TITLE
Building on ubuntu 20.04, needed to replace PyObject_CallNoArgs with _PyObject_CallNoArg

### ISSUE THREAD

**Issue by mds2** [libfive/libfive#416]
### Description

[Followed build instructions, encountered build error.  Couldn't find PyObject_CallNoArgs on line 541 of interpreter.cpp.  My Python3 is Python3.8.  That function only exists in Python3.9.  To use in Python3.8 use the experimental version _PyObject_CallNoArg]
[Try to build libfive on Ubuntu 20.04 with Python 3.8]
[I expected to encounter some fiddly build issues, and I did.  So, working as expected.]
[NA]

### Versions

- Operating system: [Ubuntu 20.04]
- `libfive` commit hash: [533045072d679cba7d400f1b2a97a2cc31efb91e]
  - Is this the latest commit to `master`?  [yes]
- Qt version (if applicable): [NA]

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

I haven't actually tried using Studio with python, so, my fix might not actually work.  But it lets me build the platform, and I'm perfectly fine just using scheme for it.

If anyone else encounters this issue, and has trouble building, the following code diff worked as a workaround for me

```
diff --git a/studio/src/python/interpreter.cpp b/studio/src/python/interpreter.cpp
index f6af8fe4..689dbf91 100644
--- a/studio/src/python/interpreter.cpp
+++ b/studio/src/python/interpreter.cpp
@@ -538,7 +538,7 @@ void Interpreter::eval(QString script)
         // the printed traceback into a string.
         auto io_mod = PyImport_ImportModule("io");
         auto string_io = PyObject_GetAttrString(io_mod, "StringIO");
-        auto new_stderr = PyObject_CallNoArgs(string_io);
+        auto new_stderr = _PyObject_CallNoArg(string_io);
         PySys_SetObject("stderr", new_stderr);
 
         // Print the error to our StringIO, then decode it into a QString
```

**Comment by mkeeter** [comment]
Thanks, fixed!  `PyObject_CallNoArgs` isn't part of the Python 3.8 API, and I'm a little iffy on using the underscored version, so I switched to `PyObject_CallObject` instead.
