### ISSUE TITLE
Use of libstdc++ vs libc++ on macOS

### ISSUE THREAD

**Issue by szhorvat** [libfive/libfive#429]
When I build with LLVM Clang on macOS, I get a bunch of warnings like this:

```
clang: warning: -Z-reserved-lib-stdc++: 'linker' input unused [-Wunused-command-line-argument]
```

I think these appear because of an explicit linking to `libstdc++`. While the program _seems_ to work fine when compiled this way, mixing libc++ and libstdc++ can't be without consequences (note that the Qt that Studio links to is using libc++)

CMakeLists.txt contains:

```cmake
    if (${CMAKE_CXX_COMPILER_ID} STREQUAL "AppleClang")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -stdlib=libc++")
    else()
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -lstdc++")
    endif()
```

Why is this necessary?  These are `CMAKE_CXX_FLAGS` not `CMAKE_C_FLAGS` so an explicit `-lstdc++` should not be necessary. Also, why not let the compiler use the default C++ standard library implementation of the system?  Was this perhaps needed only pre-macOS-10.9, but now it's obsolete? Can we remove this?

I only ever had to use an explicit `-lstdc++` or `-lc++` when _statically_ linking a C (not C++) program against a library that has a pure C API but is (partly) implemented in C++.

**Comment by mkeeter** [comment]
Goooood question!

This may be a historical artifact.  I removed it and built on macOS + Linux, and everything seems fine, so let's just take it out (bc2cd87de1f8633691d5c7c644ece8073e3b3abd) and see if anyone complains.
