### ISSUE TITLE
Y-up

### ISSUE THREAD

**Issue by omgitsraven** [libfive/libfive#46]
Is there any hope of adding a Y-up option for the display in Studio :) It would mainly just impact the way the mouse orbit controls work; when I rotate the shape so that Y is up, I'm not able to pivot around Y to view the sides without pivoting around X first...

**Comment by mkeeter** [comment]
Yup, I'm eventually planning to add arcball rotation as an alternate mode.  Not sure when I'll get to it, so I'll leave this open as a tracking issue.

**Comment by Paul-Wray** [comment]
Some controls for the various orthogonal views would be nice too. 
Or perhaps some scheme fns to control the view, set up a turntable, resolution etc.

**Comment by mkeeter** [comment]
Agreed, I think I'd prefer having Scheme functions to replace the existing magic comments.

**Comment by mkeeter** [comment]
Y-up mode is now in the latest commit to `master`, in the `View -> Rotation mode` menu.

I'm just coming off a deep dive in the kernel (to make meshing faster + more robust!), and plan to devote a bit more time to the UI in coming months.

**Comment by omgitsraven** [comment]
Ahh, thank you :D
