### ISSUE TITLE
SEGV (null ptr read) in multithreaded evaluator

### ISSUE THREAD

**Issue by doug-moen** [libfive/libfive#472]
The code that Matt provided in discussion #468 causes a crash in the libfive evaluator if multithreading is enabled.

I am running Fedora Workstation linux.

There will be a separate pull request containing a failing test case added to the libfive test suite.

**Comment by doug-moen** [comment]
The bug is actually in the documentation. In `libfive/include/libfive/render/brep/settings.hpp`, in `struct BRepSettings`, it says:
```
    /*  Number of worker threads to use while meshing.  Set as 0 to use the
     *  platform-default number of threads. */
    unsigned workers;
```
If you actually set `workers` to 0 then the evaluator crashes. Two suggested fixes:
1. Change the documentation to match the behaviour. `workers` must be >= 0.
2. Change the behaviour to match the documentation. If `workers==0` then set workers to `std::thread::hardware_concurrency()` from header `<thread>`.

**Comment by mkeeter** [comment]
Thanks, I decided to fix the docs instead of plumbing changes through all of the rendering pipelines.
