### ISSUE TITLE
Emacs?

### ISSUE THREAD

**Issue by Kreyren** [libfive/libfive#477]
Is there a way to get the render preview in emacs?

**Comment by occivink** [comment]
To use an external editor, use `File > Open as viewer`, then the file will be reloaded everytime it is modified on disk. It would make sense to add a commandline option to directly open in this mode.

**Comment by Kreyren** [comment]
> To use an external editor, use `File > Open as viewer`, then the file will be reloaded everytime it is modified on disk. It would make sense to add a commandline option to directly open in this mode. -- @occivink (https://github.com/libfive/libfive/issues/477#issuecomment-997786033)

That doesn't work for me as changing the file in the external editor causes fatal failure:

![2021-12-20_13-54](https://user-images.githubusercontent.com/11302521/146770249-3eebb895-6f23-46e7-8b42-372af1ed3817.png)

FWIW i was told that the inspekt3d is fully integrated in geiser-guile to provide the interactive preview in emacs, but none seems to know how to configure it (asked on emacs's mailing list as well).

**Comment by Kreyren** [comment]
CC @bsima -- https://github.com/libfive/libfive/issues/274#issuecomment-735953692

Can you elaborate how are you using inspekt3d in emacs please? I am unable to figured it out and the repo is 404 on gitlab.

**Comment by Kreyren** [comment]
Moved in https://github.com/libfive/libfive/discussions/510
