### ISSUE TITLE
Q: Why is the scheme stdlib/shapes.scm generated from C++?

### ISSUE THREAD

**Issue by Kreyren** [libfive/libfive#479]
Makes it kinda painful to contribute to as python is limited on functionality in comparison.

**Comment by Kreyren** [comment]
The generation file seems to be deprecated.. i found branch working on purely scheme and then code in https://github.com/libfive/libfive/tree/master/libfive/bind/guile/libfive

**Comment by mkeeter** [comment]
I want to support both C, C++, Python, and Scheme bindings, without having to rewrite shapes in each language.  Autogenerating from C/C++ then using FFI from higher-level languages makes that possible!  Details are in the overview doc [here](https://github.com/libfive/libfive/tree/master/libfive/stdlib#overview)
