### ISSUE TITLE
Q: Is there a non-complicated way to make trapezoid-like shape with 6 points?

### ISSUE THREAD

**Issue by Kreyren** [libfive/libfive#483]
i am trying to define an alluminium profile/extrusion to design a brace for the Z-Axis on Creality Ender 3 printer:

![2021-12-20_13-42](https://user-images.githubusercontent.com/11302521/146768784-b221572e-1203-428b-90cb-bdbd3e1331b5.png)

with dimensions:
![2021-12-20_13-44](https://user-images.githubusercontent.com/11302521/146769062-7db0e3ff-c19a-456e-9637-f1b18e85dec4.png)

and i got this so far:
```scheme
(set-bounds! [-10 -10 -10] [10 10 10])
(set-quality! 8)
(set-resolution! 100)

;;;; To be contributed
(define cube-centered box-mitred-centered)
;; NOTE(Krey): Make `(cube)` to display `(cube [0 0 0] [1 1 1])`

(define (extrusion x)
  "FIXME-DOCS"
    (difference
      (cube-centered [x x 0.01] [0 0 0])
      (cylinder (* x 0.10) 0.5 [0 0 -0.25])
    )
)
  
(extrusion 1)

;;(extrude-z (polygon 1 4 [0 0]) 0 0.01)
```

Is there a way to define the trapezoid as **ONE** 2D object (meaning without using other shapes to create the trapezoid) centered on `[0 0 0]` to make it more maintainable by reducing the complexity?

**Comment by Kreyren** [comment]
FWIW preferably if i could do something like a one polygon which points can be defined in coordinates for scaling

**Comment by occivink** [comment]
I'm not a pro, but for a convex shape like this I would use the intersection of `half_space` shapes defined by each edge. So for a unit cube (in python):
```
extrude_z(
  intersection(
    half_space([1,0,0], [1,0,0]),
    half_space([0,1,0], [0,1,0]),
    half_space([-1,0,0], [-1,0,0]),
    half_space([0,-1,0], [0,-1,0])
  ),
  -1, 1
);
```

For non-convex shapes... well they can be decomposed into convex shapes.

**Comment by Kreyren** [comment]
> I'm not a pro, but for a convex shape like this I would use the intersection of half_space shapes defined by each edge. So for a unit cube (in python): -- @occivink (https://github.com/libfive/libfive/issues/483#issuecomment-997937743)

I converted it in scheme and gave it 1.5h of time, but i can't figure out how to make it to work that way:

```scheme
(set-bounds! [-10 -10 -10] [10 10 10])
(set-quality! 8)
(set-resolution! 10)

(define (test x y z)
  "FIXME-DOCS"
  ;;(extrude-z
    (intersection
      (half-space [0 0 7.65] [0 0 0])
      (half-space [0 7.65 0] [0 0 0])
      ;;(half-space [0 0 0] [0 0 0])
      ;;(half-space [0 0 0] [0 0 0])
    )
  ;;0 1)
  )
  
(test 1 2 3)
```

![2021-12-21_01-46](https://user-images.githubusercontent.com/11302521/146852041-77bc123f-62c6-4cb0-8495-7062f71314a7.png)

Where i tried to define coordinates for the center of the alluminium extrusion/profile to define the polygonal shape.

Couldn't also make it to work to define a complex shape to do the trapezoid.

**Comment by Kreyren** [comment]
I reworked the shape to utilize mirroring:

![2021-12-21_05-26](https://user-images.githubusercontent.com/11302521/146884096-b88a30cd-57a2-4a5f-b69e-efdd2b81f214.png)

So it doesn't need the trapezoid and should work with just simple cutting of difference
