### ISSUE TITLE
Workbench for FreeCAD?

### ISSUE THREAD

**Issue by Kreyren** [libfive/libfive#488]
Is it in the scope of this project to provide FreeCAD workbench or is there a way to do various simulations to optimize the design?

See https://forum.freecadweb.org/viewtopic.php?f=10&t=64656&p=555005#p555005

**Comment by Kreyren** [comment]
Figured out that those are not compatible as both use different rendering kernels.

**Comment by mkeeter** [comment]
Yeah, it would be a big challenge – I don't know much about FreeCAD's internals, but I believe it's using OpenCASCADE, which is a NURBS / b-rep kernel (vs libfive's custom f-rep kernel).
