### ISSUE TITLE
Including Obj File

### ISSUE THREAD

**Issue by dileepmaloth** [libfive/libfive#501]
Can you please let me know where should I give my obj file to the code? so that I can apply boolean operations on the meshes.

**Comment by mkeeter** [comment]
Hi @dileepmaloth ,

Right now, there's no way to import meshes into `libfive`, because it's using a completely different internal representation.  It's theoretically possible, but would require implementing an oracle to turn the mesh into a distance field.

Discussed in #338 and #446
