### ISSUE TITLE
nodejs bindings

### ISSUE THREAD

**Issue by lf94** [libfive/libfive#530]
While not done, I figured it'd be good to open this issue that others can use to track between the two projects.

https://github.com/lf94/node-libfive

The main library bindings are done but not the stdlib bindings. There's also a wrapper I'm working on as I use it.

As a little test I made a shipping box: https://github.com/lf94/node-libfive/blob/main/examples/shipping-box.js

The whole thing has a little under 2 weeks of on-off work, so still a bit ways to go. Really just pecking away when I've got the time.

**Comment by lf94** [comment]
I took a mental day to chill and do the rest of the mindless work of writing bindings. So the bindings are done. I think it'd be beneficial to get these merged alongside the Python and Guile bindings. Maintaining this in its own project feels like it's going to get lost to time.

**Comment by lf94** [comment]
@mkeeter let me know how you'd like to move forward :slightly_smiling_face:

**Comment by mkeeter** [comment]
At this point, I'm hesitant to put them into the main repository for fear of them growing stale; it's not something that I would actively be maintaining, and I've had issues with contributions rotting in the past.

Adding a link in the README would be excellent, and if the bindings hit critical mass of users / developers, I'd be happy to reconsider.

**Comment by lf94** [comment]
Sounds good to me
