### ISSUE TITLE
Compiling on Fedore FC37

### ISSUE THREAD

**Issue by gsohler** [libfive/libfive#536]
I tried to  compile like in the description

mkdir build
cd build
cmake ..
make -j4

it failed at about 75% while linking libfive-test

then i have done

make and i have seen the verbose error:

gigl@fedora build]$ make 
[ 44%] Built target libfive
[ 46%] Built target libfive-stdlib
[ 69%] Built target libfive-test
[ 69%] Generating libfive/kernel.go
No such file or directory
make[2]: *** [libfive/bind/guile/CMakeFiles/libfive-guile.dir/build.make:83: libfive/bind/guile/libfive/kernel.go] Error 1
make[1]: *** [CMakeFiles/Makefile2:283: libfive/bind/guile/CMakeFiles/libfive-guile.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

where can be the error ? i have never heard from a kernel.go file

[gigl@fedora build]$ ls libfive/bind/guile/libfive/kernel.go
ls: cannot access 'libfive/bind/guile/libfive/kernel.go': No such file or directory
[gigl@fedora build]$ ls libfive/bind/guile/
CMakeFiles/          cmake_install.cmake  Makefile             
[gigl@fedora build]$ ls libfive/bind/guile/
CMakeFiles  cmake_install.cmake  Makefile
[gigl@fedora build]$ 

the file is really missing but i dont have any clue how to continue

============
BTW i tried to compile libfive studio before without guile.
it crashed on very first start
on  second startup i have seen the sphere and i could change  its size

i did not make to get correct syntax for a box

i  could not get any tutorial  or example running probably due to missing guile
(the ' character in the comments was a big  issue)

let  me know

### Description

[Description of the issue]
[Steps to reproduce]
[What did you expect to happen?  What happened?  All the time?]
[Are there any error messages printed to the console?]

### Versions

- Operating system: [here]
- `libfive` commit hash: [here]
  - Is this the latest commit to `master`?  [yes]
- Qt version (if applicable): [here]

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

### Common questions
[Delete this section if not relevant]

If this is a behavior issue, does the test suite (`libfive/test/libfive-test`) pass?

If this is a graphics issue on Linux, report the results of updating your graphics drivers (and switching to binary graphics drivers if applicable).

If there are error messages in the console, have you searched for them and followed up on any promising leads?

**Comment by mkeeter** [comment]
I'm sorry, but this issue does not give me enough information to offer any assistance.  In addition, **the entire issue template is ignored**.

--------------------------------------------------------------------------------

For example:

> it failed at about 75% while linking libfive-test

Okay, how did it fail?  Please provide the specific console logs.  How did you try to resolve this?

>  it crashed on very first start

In this case, providing a backtrace would be necessary.

--------------------------------------------------------------------------------

The only hint I can provide is that `libfive/bind/guile/libfive/kernel.go` is Guile bytecode, which should be compiled by the build system.  If this doesn't work, then perhaps you don't have Guile installed.  Did you follow the build instructions in the README?  Did you read the console output and confirm that every step completed without errors?

--------------------------------------------------------------------------------

Please reopen the ticket with more useful diagnostic information and the template filled on.  I don't have an FC37 machine, so you will have to do the **vast majority** of the legwork in diagnosing and fixing the issue.
