### ISSUE TITLE
missing 'g++' package in Ubuntu instructions

### ISSUE THREAD

**Issue by athompso** [libfive/libfive#567]
### Description

The Ubuntu instructions are good, but miss installing a c++ compiler.
cmake flags this immediately, and the user has to know to manually install "g++" to resolve the issue.

### Versions

- Operating system: Ubuntu 20.04 LTS, Ubuntu 22.04 LTS
- `libfive` commit hash: n/a
  - Is this the latest commit to `master`?  yes
- Qt version (if applicable): n/a

### Additional Information

PR #566 resolves the problem for users blindly copy-and-pasting from the instructions.  If you already have a different C++ compiler installed, you're probably not copy-and-pasting that "apt install" line anyway.

**Comment by mkeeter** [comment]
Fixed in #566, thanks!
