### ISSUE TITLE
Make fails on heightmap.cpp.o with "integer value -1 outside valid range"

### ISSUE THREAD

**Issue by mirkov** [libfive/libfive#572]
### Description

I am building libffi from sources on MacBook M2

- Updated dependencies via HomeBrew
- Ran cmake. It had problems. See [issue 571](https://github.com/libfive/libfive/issues/571)  on how I fixed them
- Make did not run through. It failed on `heightmap.cpp.o`

```
make
[  1%] Building CXX object libfive/src/CMakeFiles/libfive.dir/render/discrete/heightmap.cpp.o
In file included from /Users/mirkov/Documents/mv-program-files/libfive/libfive/src/render/discrete/heightmap.cpp:19:
In file included from /Users/mirkov/Documents/mv-program-files/libfive/libfive/src/../include/libfive/render/discrete/heightmap.hpp:14:
In file included from /Users/mirkov/Documents/mv-program-files/libfive/libfive/src/../include/libfive/render/discrete/voxels.hpp:15:
/Users/mirkov/Documents/mv-program-files/libfive/libfive/src/../include/libfive/render/axes.hpp:42:16: error: integer value -1 is outside the valid range of values [0, 7] for this enumeration type [-Wenum-constexpr-conversion]
               static_cast<Axis>(-1);
               ^
1 error generated.
make[2]: *** [libfive/src/CMakeFiles/libfive.dir/render/discrete/heightmap.cpp.o] Error 1
make[1]: *** [libfive/src/CMakeFiles/libfive.dir/all] Error 2
```
### Versions

- Operating system: MacOS Sonoma 14.5
- `libfive` commit hash: 4c59b11
  - Is this the latest commit to `master`?  yes
- Qt version (if applicable): 5 & 6

### Additional Information

My cmake may not have executed perfectly. See [issue 571](https://github.com/libfive/libfive/issues/571) on problem I experienced and how I tried to fix it.

**Comment by mkeeter** [comment]
Can you check that the above commit fixes your issue?
