### ISSUE TITLE
Test `Cache::fromAffine / Empty` breaks compilation on older Mac OS X

### ISSUE THREAD

**Issue by follower** [libfive/libfive#91]
Compilation on Mac OS X 10.8 (and likely 10.9 and possibly some Linuxi) is broken by the recent addition of the test`Cache::fromAffine / Empty`:

<https://github.com/libfive/libfive/blob/d853cf057e689742a9add6e5871f5027fca0c53d/libfive/test/cache.cpp#L234>

It results in this error:

```
/<path>/libfive/libfive/test/cache.cpp:279:33: error: chosen constructor is explicit in
      copy-initialization
        auto a_ = t->fromAffine({});
                                ^~
/usr/bin/../lib/c++/v1/map:838:14: note: constructor declared here
    explicit map(const key_compare& __comp = key_compare())
             ^
/<path>/libfive/libfive/src/../include/libfive/tree/cache.hpp:80:50: note: passing argument to parameter
      'ns' here
    Node fromAffine(const std::map<Node, float>& ns);
                                                 ^
1 error generated.
make[2]: *** [libfive/test/CMakeFiles/libfive-test.dir/cache.cpp.o] Error 1
make[1]: *** [libfive/test/CMakeFiles/libfive-test.dir/all] Error 2
make: *** [all] Error 2
```

It seems like this is a "known issue":

 * ["'chosen constructor is explicit in copy-initialization error' with clang++ 4.2"](https://stackoverflow.com/questions/17264067/chosen-constructor-is-explicit-in-copy-initialization-error-with-clang-4-2) 

 * ["macOS <= 10.9: error: chosen constructor is explicit in copy-initialization #339"](https://github.com/USCiLab/cereal/issues/339) which includes the explanation "Sounds like whatever version of clang Apple is using there has an explicit default constructor for map."

My initial attempt to fix was:

```c++
auto a_ = t->fromAffine(std::map<Cache::Node, float>{});
```

However that results in:

```
/<path>/libfive/libfive/test/cache.cpp:279:47: error: 'Node' is a private member of 'Kernel::Cache'
      auto a_ = t->fromAffine(std::map<Cache::Node, float>{});
                                              ^
/<path>/libfive/libfive/src/../include/libfive/tree/cache.hpp:35:42: note: implicitly declared private
      here
    typedef std::shared_ptr<Tree::Tree_> Node;
                                         ^
1 error generated.
make[2]: *** [libfive/test/CMakeFiles/libfive-test.dir/cache.cpp.o] Error 1
make[1]: *** [libfive/test/CMakeFiles/libfive-test.dir/all] Error 2
make: *** [all] Error 2
```

I am able to get it to compile (and seemingly test successfully) with the non-`typedef`'d equivalent:

```c++
auto a_ = t->fromAffine(std::map<std::shared_ptr<Tree::Tree_>, float>{});
```

I can submit a PR for the latter but wondered if you'd prefer a change in visibility for the `Node` typedef.

**Comment by mkeeter** [comment]
Ah, this is an old nemesis where different compilers are more or less picky about initialization.

The commit above should fix it; re-open if you're having issues.
