### ISSUE TITLE
Auto-bounds is clipping the shape

### ISSUE THREAD

**Issue by omgitsraven** [libfive/libfive#95]
In the following example:
```
(sequence
  (torus 0.55 0.06)
  (rotate-x 2.72)
  (scale-x 1.3)
  (move #[0 0.0125 -0.9])
  (rotate-y -0.1)
  (move #[0.085 0 0])
)
```
the right edge of the torus is shaved off by the auto-bounds. (You might have to turn up the resolution to see it.)

Interestingly, for a MUCH more dramatic example, just comment out the last `move` command; it's almost completely clipped for some reason, despite what a tiny displacement that is!

**Comment by mkeeter** [comment]
Weird!  I'll look into it.

**Comment by mkeeter** [comment]
This should be fixed now (that's what I get for only testing this function with perfectly symmetric shapes 😛 )
